name: Setup jcli
description: Setup jcli with specified version
inputs:
  version:
    description: The jcli version
    required: true
  jet-endpoint:
    description: The Jet API endpoint URL
    required: true
runs:
  using: composite
  steps:
    - name: Calculate jcli fileName
      shell: bash
      run: |
        os_part="${{ runner.os == 'Linux' && 'unknown-linux-gnu' || 'apple-darwin' }}"
        arch_part="${{ runner.arch == 'X64' && 'x86_64' || 'aarch64' }}"
        echo "JCLI_FILE_NAME=jcli-$arch_part-$os_part" >> $GITHUB_ENV

    - if: ${{ inputs.version == 'latest' }}
      uses: robinraju/release-downloader@v1.8
      with:
        repository: byzanteam/jcli
        latest: true
        fileName: ${{ env.JCLI_FILE_NAME }}

    - if: ${{ inputs.version != 'latest' }}
      uses: robinraju/release-downloader@v1.9
      with:
        repository: byzanteam/jcli
        tag: ${{ inputs.version }}
        fileName: ${{ env.JCLI_FILE_NAME }}

    - name: Move jcli
      shell: bash
      run: |
        mkdir -p $HOME/.local/bin
        mv ${{ env.JCLI_FILE_NAME }} $HOME/.local/bin/jcli
        chmod +x $HOME/.local/bin/jcli
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Setup jcli configuration
      shell: bash
      run: |
        mkdir -p ~/.config/jcli
        echo '{"jetEndpoint": "${{ inputs.jet-endpoint }}"}' > ~/.config/jcli/config.json
